---
  - name: run certbot role
    include_role:
      name: certbot

  - name: link letsencrypt certificate
    file:
      src: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
      dest: "{{ ssl_dir }}/{{ domain }}.crt"
      state: link
      force: yes
    notify: reload nginx

  - name: link letsencrypt key
    file:
      src: /etc/letsencrypt/live/{{ domain }}/privkey.pem
      dest: "{{ ssl_dir }}/{{ domain }}.key"
      state: link
      force: yes
    notify: reload nginx
